version: '3.8'

services:
  db:
    image: 'postgres:16.1-alpine'
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
    ports:
      - "5432:5432"