version: '3'

services:
  app:
    image: 'andrewsynkov/management-service:latest'
    build: .
    container_name: app
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: 'postgres:16.1-alpine'
    container_name: db
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
    ports:
      - "5432:5432"