name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
env:
  DOCKER_IMAGE_NAME: andrewsynkov/management-service:latest
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_DB: postgres-db
          POSTGRES_USER: postgres-user
          POSTGRES_PASSWORD: postgres-password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
      - name: Execute Gradle build
        run: ./gradlew clean bootJar
      - name: Login to Docker
        run: echo ${{secrets.DOCKER_REGISTRY_ACCESS_TOKEN}} | docker login -u andrewsynkov --password-stdin
      - name: Build Docker image
        run: docker build --platform linux/amd64/v2 -t management-service . --file Dockerfile --tag ${{env.DOCKER_IMAGE_NAME}}
      - name: Publish Docker image
        run: docker push ${{env.DOCKER_IMAGE_NAME}}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{secrets.SERVER_SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.SERVER_HOST}} > ~/.ssh/known_hosts
      - name: Create docker compose env file
        run: |
          touch .env
          echo "TODOIST_API_TOKEN=${{secrets.TODOIST_API_TOKEN}}" >> .env
          echo "TODOIST_HOST=${{secrets.TODOIST_HOST}}" >> docker/.env
          echo "TELEGRAM_TOKEN=${{secrets.TELEGRAM_TOKEN}}" >> docker/.env
          echo "TELEGRAM_BOT=${{secrets.TELEGRAM_BOT}}" >> docker/.env
          echo "TELEGRAM_CHAT_ID=${{secrets.TELEGRAM_CHAT_ID}}" >> docker/.env
          echo "DB_HOST=db" >> docker/.env
          echo "DB_NAME=management-service-db" >> docker/.env
          echo "DB_USER=${{secrets.DB_USER}}" >> docker/.env
          echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> docker/.env
          echo "DB_PORT=5432" >> docker/.env
      - name: Send env file to remote server
        run: scp .env ${{secrets.SSH_SERVER_USER}}@${{secrets.SERVER_HOST}}:/${{secrets.SSH_SERVER_USER}}
      - name: Docker compose up
        run: ssh ${{secrets.SSH_SERVER_USER}}@${{secrets.SERVER_HOST}} "docker compose up -d"
      - name: Remove env files
        run: |
          ssh ${{secrets.SSH_SERVER_USER}}@${{secrets.SERVER_HOST}} 'rm /${{secrets.SSH_SERVER_USER}}/.env'
          rm .env
      - name: Remove ssh files
        run: |
          rm ~/.ssh/id_rsa
          rm ~/.ssh/known_hosts