name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
      - name: Execute Gradle build
        run: ./gradlew clean test bootJar
      - name: Build Docker image
        run: docker build --platform linux/amd64/v2 -t management-service . --tag andrewsynkov/management-service:latest
      - name: Publish Docker image
        run: docker push andrewsynkov/management-service:latest
